// apps/frontend/src/App.vue
<script setup lang="ts">
import { onMounted, watch } from 'vue'
import { socket, Toast } from './utils'
import emitter from '@/utils/eventEmitter'
import { useUserStore } from './stores'

const userStore = useUserStore()

watch(
  () => userStore.token,
  async () => {
    if (!userStore.token) return
    console.log('token update, get user info')
    await userStore.getUserInfo()
    await userStore.getUserCollectListOfPostId()
    await userStore.getUserFollowList()

    // websocket
    socket.emit('login', userStore.userInfo?.user_id)
  }
)

// api
emitter.on('API:UN_AUTH', (message: string) => {
  Toast.show({
    msg: message,
    type: 'error',
  })
  userStore.removeToken()
})

emitter.on('API:BAD_REQUEST', (message: string) => {
  Toast.show({
    msg: message,
    type: 'error',
  })
})

onMounted(async () => {
  // 主题
  document.body.dataset.theme = localStorage.getItem('theme') as
    | string
    | undefined

  if (userStore.token) {
    await userStore.getUserInfo()
    await userStore.getUserCollectListOfPostId()
    await userStore.getUserFollowList()
  }

  window.addEventListener('offline', () => {
    Toast.show({
      msg: '不知道谁的网络出现了点问题😢',
      type: 'error',
    })
  })

  window.addEventListener('online', () => {
    Toast.show({
      msg: '满血复活😊',
      type: 'success',
    })
  })

  let lastTime = 0
  window.addEventListener('scroll', () => {
    const now = Date.now()
    if (now - lastTime > 500) {
      emitter.emit('TAB:CLOSE_AVATAR_WIDGET')
      lastTime = now
    }
  })
})
</script>

<template>
  <router-view />
</template>

<style scoped lang="scss"></style>

// apps/admin/src/App.tsx
import { useEffect } from 'react'
import AppRouter from './router'
import { useStatusStore, useUserStore } from './stores'
import { useNavigate } from 'react-router-dom'
import { RoutePath } from './router/router'
import emitter from './utils/eventEmitter'
import { Toast } from './utils'
import i18n from './i18n'

function App() {
  const navigate = useNavigate()

  useEffect(() => {
    const { token, removeToken, permissions, setPermissions } =
      useUserStore.getState()

    if (!token) {
      removeToken()
      navigate(RoutePath.login)
      return
    }

    setPermissions(permissions)
  }, [navigate])

  useEffect(() => {
    console.log('app effect')
    const { currentTheme, currentLanguage } = useStatusStore.getState()
    // 主题
    document.body.dataset.theme = currentTheme

    // 语言
    i18n.changeLanguage(currentLanguage)
    console.log(currentLanguage)

    // api
    const { removeToken } = useUserStore.getState()
    const unAuthOff = emitter.on('API:UN_AUTH', (message: string) => {
      Toast.show({
        msg: message,
        type: 'error',
      })
      removeToken()
      navigate(RoutePath.login)
    })

    const forbiddenOff = emitter.on('API:FORBIDDEN', (message: string) => {
      Toast.show({
        msg: message,
        type: 'error',
      })
    })

    return () => {
      unAuthOff()
      forbiddenOff()
    }
  }, [navigate])

  return <AppRouter />
}

export default App
